const products = [
  { name: "The Sovereign Jean", price: "$240", tone: "bg-[linear-gradient(135deg,#273344,#10151d_55%,#8793a2)]", tag: "Best seller" },
  { name: "HOD Rhinestone Trucker", price: "$180", tone: "bg-[linear-gradient(135deg,#d2c7b7,#6b625a_48%,#eee9df)]", tag: "New arrival" },
  { name: "Domination Hoodie", price: "$120", tone: "bg-[linear-gradient(135deg,#343434,#0b0b0b_55%,#5d5d5d)]", tag: "Limited" },
  { name: "The House Tee", price: "$75", tone: "bg-[linear-gradient(135deg,#eee8dc,#9a938a_50%,#1c1c1c)]", tag: "Essential" },
];

function Sparkle({ className = "" }: { className?: string }) { return <span aria-hidden="true" className={`font-serif text-rhinestone ${className}`}>✦</span>; }
function Button({ children }: { children: React.ReactNode }) { return <a href="#shop" className="inline-flex items-center justify-center border border-ivory/70 px-6 py-3 font-mono text-[10px] uppercase tracking-[.2em] transition-colors hover:bg-ivory hover:text-obsidian">{children}</a>; }
function ProductCard({ product }: { product: typeof products[number] }) { return <article className="group"><div className={`grain relative aspect-[4/5] overflow-hidden ${product.tone}`}><div className="absolute inset-4 border border-ivory/30 opacity-0 transition-opacity group-hover:opacity-100"/><div className="absolute left-4 top-4 font-mono text-[9px] uppercase tracking-[.15em] text-obsidian/70">{product.tag}</div><div className="absolute bottom-5 left-1/2 -translate-x-1/2 font-serif text-[110px] italic leading-none text-ivory/20 transition-transform duration-500 group-hover:scale-110">H</div></div><div className="flex items-start justify-between gap-4 py-4"><div><h3 className="font-serif text-xl italic">{product.name}</h3><p className="mt-1 font-mono text-[10px] uppercase tracking-[.15em] text-rhinestone">Signature collection</p></div><p className="font-mono text-xs">{product.price}</p></div></article>; }
export default function Home() { return <main id="top">
  <section className="grain relative flex min-h-[90vh] items-end overflow-hidden bg-graphite px-5 pb-10 pt-32 md:min-h-screen md:px-10 md:pb-16"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_72%_36%,#555149_0%,#242424_33%,#0c0c0c_73%)] opacity-80"/><div className="absolute right-[12%] top-[19%] h-[46vw] w-[26vw] rotate-12 border border-rhinestone/20 bg-[linear-gradient(100deg,transparent_20%,#c9c0b1_48%,#303030_54%,transparent_72%)] opacity-50 blur-[1px]"/><div className="relative z-10 max-w-5xl"><p className="mb-5 font-mono text-[10px] uppercase tracking-[.3em] text-rhinestone">Vol. 04 — The Sovereign Collection</p><h1 className="max-w-4xl font-serif text-[clamp(4.5rem,13vw,12rem)] leading-[.76] tracking-[-.08em]">Built to<br/><span className="ml-[12vw] italic text-rhinestone">be</span><br/>witnessed.</h1><div className="mt-10 flex flex-col items-start gap-5 sm:flex-row sm:items-center"><Button>Shop the drop</Button><p className="max-w-xs font-mono text-[10px] uppercase leading-relaxed tracking-[.1em] text-rhinestone">Rhinestone denim and elevated essentials for the ones who refuse to blend in.</p></div></div><p className="absolute bottom-8 right-10 hidden font-mono text-[9px] uppercase tracking-[.2em] text-rhinestone md:block">Scroll to enter <span className="ml-3">↓</span></p></section>
  <section id="shop" className="bg-ivory px-5 py-20 text-obsidian md:px-10 md:py-28"><div className="mb-10 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-blood">01 / The drop</p><h2 className="mt-3 font-serif text-5xl italic tracking-tight md:text-7xl">New arrivals</h2></div><a href="#shop" className="hidden border-b border-obsidian pb-1 font-mono text-[10px] uppercase tracking-[.15em] sm:block">View all pieces →</a></div><div className="grid gap-x-4 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{products.map((p) => <ProductCard key={p.name} product={p}/>)}</div></section>
  <section id="lookbook" className="bg-obsidian px-5 py-20 md:px-10 md:py-28"><div className="grid gap-10 md:grid-cols-12 md:items-end"><div className="md:col-span-4"><p className="font-mono text-[10px] uppercase tracking-[.25em] text-blood">02 / Lookbook</p><h2 className="mt-4 font-serif text-6xl italic leading-[.85] md:text-8xl">Make an<br/>entrance.</h2><p className="mt-8 max-w-xs font-mono text-xs uppercase leading-relaxed tracking-[.12em] text-rhinestone">For late nights, bright lights, and every room that needs a little more presence.</p></div><div className="grid gap-4 sm:grid-cols-2 md:col-span-8"><div className="grain relative aspect-[3/4] overflow-hidden bg-[linear-gradient(160deg,#a69b91,#353434_45%,#111)]"><div className="absolute bottom-5 left-5 font-serif text-5xl italic text-ivory/80">01</div></div><div className="grain relative mt-8 aspect-[3/4] overflow-hidden bg-[linear-gradient(30deg,#1a1d2b,#2946d3_45%,#d8d1c4)]"><div className="absolute bottom-5 left-5 font-serif text-5xl italic text-ivory/80">02</div></div></div></div></section>
  <section id="story" className="bg-blood px-5 py-24 text-ivory md:px-10 md:py-36"><div className="grid gap-12 md:grid-cols-12"><div className="md:col-span-3"><Sparkle className="text-4xl"/><p className="mt-5 font-mono text-[10px] uppercase leading-relaxed tracking-[.22em]">03 / The house</p></div><div className="md:col-span-8 md:col-start-5"><h2 className="font-serif text-[clamp(3.5rem,8vw,8rem)] leading-[.82] tracking-[-.05em]">Not made for<br/><span className="italic text-rhinestone">the background.</span></h2><p className="mt-10 max-w-lg font-mono text-xs uppercase leading-[1.8] tracking-[.12em] text-ivory/80">House of Domination is a uniform for the unapologetic. Every piece is cut with intention, finished by hand, and made to take up space. We believe your clothes should enter the room before you do.</p><div className="mt-10"><Button>Read our story</Button></div></div></div></section>
</main>; }
